-- MySQL Script generated by MySQL Workbench
-- Fri Jul 16 08:21:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ces
-- -----------------------------------------------------
-- Database of Cutie And Sweet Moda Fashion.
-- 

-- -----------------------------------------------------
-- Schema ces
--
-- Database of Cutie And Sweet Moda Fashion.
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ces` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `ces` ;

-- -----------------------------------------------------
-- Table `ces`.`responsaveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ces`.`responsaveis` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `senha` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_user_id` (`user_id` ASC) INVISIBLE,
  CONSTRAINT `user_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ces`.`responsaveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ces`.`default`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ces`.`default` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `owner` VARCHAR(150) NULL,
  `cnpj` VARCHAR(100) NOT NULL,
  `address` VARCHAR(250) NOT NULL,
  `link_address` TEXT NULL,
  `footer_text` TEXT NOT NULL,
  `phone` VARCHAR(14) NULL,
  `whatsapp` VARCHAR(14) NULL,
  `telegram` VARCHAR(14) NULL,
  `instagram` TEXT NULL,
  `facebook` TEXT NULL,
  `email` VARCHAR(100) NULL,
  `email_two` VARCHAR(100) NULL,
  `wellcome_message` TEXT NULL,
  `image` TEXT NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `default_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `default_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ces`.`responsaveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ces`.`about`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ces`.`about` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `text` TEXT NOT NULL,
  `mission` VARCHAR(250) NULL,
  `vision` VARCHAR(250) NULL,
  `values` VARCHAR(250) NULL,
  `updated_at` DATETIME NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `about_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `about_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ces`.`responsaveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ces`.`about_gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ces`.`about_gallery` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `image` TEXT NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `about_gallery_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `about_gallery_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ces`.`responsaveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ces`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ces`.`feedback` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `text` VARCHAR(300) NULL,
  `image` TEXT NULL,
  `status` TINYINT(1) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `feedback_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `feedback_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ces`.`responsaveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ces`.`banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ces`.`banner` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `image_desktop` TEXT NOT NULL,
  `image_mobile` TEXT NOT NULL,
  `whatsapp` VARCHAR(14) NULL,
  `instagram` TEXT NULL,
  `facebook` TEXT NULL,
  `site` TEXT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `banner_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `banner_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ces`.`responsaveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ces`.`blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ces`.`blog` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `text` TEXT NOT NULL,
  `date` DATE NOT NULL,
  `video` TEXT NULL,
  `image` TEXT NOT NULL,
  `start_post` DATETIME NULL,
  `end_post` DATETIME NULL,
  `autor` VARCHAR(150) NULL,
  `font` VARCHAR(150) NULL,
  `font_link` TEXT NULL,
  `highlight` TINYINT(0) NOT NULL,
  `status` TINYINT(0) NOT NULL,
  `button` VARCHAR(100) NULL,
  `button_text` TEXT NULL,
  `button_link` TEXT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `blog_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `blog_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ces`.`responsaveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ces`.`blog_gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ces`.`blog_gallery` (
  `di` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `text_top` TEXT NULL,
  `text_bottom` TEXT NULL,
  `image` TEXT NOT NULL,
  `in_text` TINYINT(0) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `blog_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`di`),
  INDEX `blog_gallery_blog_id` (`blog_id` ASC) INVISIBLE,
  INDEX `blog_gallery_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `blog_gallery_blog_id`
    FOREIGN KEY (`blog_id`)
    REFERENCES `ces`.`blog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `blog_gallery_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ces`.`responsaveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ces`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ces`.`delivery` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `delivery_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `delivery_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ces`.`responsaveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ces`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ces`.`payment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(150) NOT NULL,
  `text` TEXT NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `payment_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `payment_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ces`.`responsaveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ces`.`category_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ces`.`category_product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `category_product_user_id` (`user_id` ASC) INVISIBLE,
  CONSTRAINT `category_product_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ces`.`responsaveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ces`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ces`.`product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `price_promo` VARCHAR(45) NULL,
  `prazo` VARCHAR(50) NULL,
  `abstract` VARCHAR(250) NULL,
  `sizes` TEXT NULL,
  `image` TEXT NOT NULL,
  `image_autor` VARCHAR(150) NULL,
  `highlight` TINYINT(0) NOT NULL,
  `image_index` TEXT NULL,
  `status` TINYINT(1) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `product_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ces`.`responsaveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ces`.`product_color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ces`.`product_color` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `exa_color` VARCHAR(50) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_color_product_id` (`product_id` ASC) INVISIBLE,
  INDEX `product_color_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `product_color_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `ces`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_color_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ces`.`responsaveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ces`.`product_gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ces`.`product_gallery` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `image` TEXT NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_gallery_product_id` (`product_id` ASC) INVISIBLE,
  INDEX `product_gallery_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `product_gallery_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `ces`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `product_gallery_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ces`.`responsaveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ces`.`category_as_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ces`.`category_as_product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cat_prod_category_id` (`category_id` ASC) INVISIBLE,
  INDEX `cat_prod_product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `cat_prod_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `ces`.`category_product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cat_prod_product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `ces`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
